// Generated by build-static.js — static hosting (GitHub Pages).
window.SITE = {
  "mode": "static",
  "web3formsKey": "795158ed-9ec8-46a7-a37e-97a9bf8d2cc7",
  "cvUrl": "/cv/Richard_Priest_CV.docx"
};
